# docker aliases for zsh

alias d='docker'

alias dat='docker attach'
alias db='docker build'
alias dbt='docker build . -t'
alias dex='docker exec'
alias dk='docker kill'
alias dl='docker logs'
alias dlf='docker logs -f'
alias dph='docker push'
alias dpl='docker pull'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dr='docker run'
alias drm='docker rm'
alias drmi='docker rmi'
alias drs='docker restart'
alias dsp='docker stop'
alias dst='docker start'
alias dtg='docker tag'
alias dtop='docker top'
alias dupd='docker update'


alias dco='docker compose'

alias dcb='docker compose build'
alias dcdn='docker compose down'
alias dcex='docker compose exec'
alias dci='docker compose images'
alias dck='docker compose kill'
alias dcl='docker compose logs'
alias dclf='docker compose logs -f'
alias dcp='docker compose pause'
alias dcph='docker compose push'
alias dcpl='docker compose pull'
alias dcps='docker compose ps'
alias dcpsa='docker compose ps -a'
alias dcr='docker compose run'
alias dcrm='docker compose rm'
alias dcrs='docker compose restart'
alias dcsp='docker compose stop'
alias dcst='docker compose start'
alias dctop='docker compose top'
alias dcunp='docker compose unpause'
alias dcup='docker compose up'

