#!/usr/bin/python

import imaplib

try:
    unread = 0
    obj = imaplib.IMAP4_SSL('imap.gmail.com',993)
    obj.login('galen.m.gold@gmail.com','czqbrydzcsjnikwv')
    obj.select()
    unread += int(len(obj.search(None, 'UnSeen')[1][0].split()))

    obj = imaplib.IMAP4_SSL('imap.gmail.com',993)
    obj.login('scoutgle@gmail.com','hzvmyzykqicchmlg')
    obj.select()
    unread += int(len(obj.search(None, 'UnSeen')[1][0].split()))

    obj = imaplib.IMAP4_SSL('imap.gmail.com',993)
    obj.login('kb6ee.ham@gmail.com','Auru5zd9!')
    obj.select()
    unread += int(len(obj.search(None, 'UnSeen')[1][0].split()))
except:
    unread = "E"

print(unread)

