#!/bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

# if [ "$instance" = fontforge ] ; then
# 	title=$(xtitle "$wid")
# 	case "$title" in
# 		Layers|Tools|Warning)
# 			echo "focus=off"
# 			;;
# 	esac
# fi

case "$class" in
	pinentry*|qalculate*)
		eval "$consequences"
		[ "$state" ] || echo "state=floating"
		;;
	MATLAB*)
		eval "$consequences"
		[ "$state" ] || echo "state=floating"
		# xdotool windowmove $wid 50% 50%
		;;
	audacious)
		eval "$consequences"
		echo "sticky=on"
		;;
	Thunderbird)
		eval "$consequences"
		echo "desktop=^2"
		;;
	Hexchat|hexchat)
		eval "$consequences"
		echo "desktop=^4"
		;;
	TelegramDesktop|telegram-desktop)
		eval "$consequences"
		echo "desktop=^5"
		;;
	discord)
		eval "$consequences"
		eval "$(xprop -id "$wid" _NET_WM_PID | awk '{ print "bin=$(readlink /proc/" $3 "/exe)"; exit }')"
		case "${bin##*/}" in
			Discord) echo "desktop=^11" ;;
			DiscordPTB) echo "desktop=^12" ;;
		esac
		;;
esac

