#! /bin/sh

sxhkd &
pipewire &
pipewire-pulse &
lxqt-policykit-agent &
setxkbmap -layout ca -model pc105 -option caps:swapescape &
$HOME/.screenlayout/default.sh &
xsetroot -cursor_name left_ptr &

nitrogen --restore &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
syncthing-gtk -m &
redshift -l 40.8:-74.4 &
kdeconnect-indicator &
$HOME/.local/bin/KopiaUI-0.8.4.AppImage &

bspc monitor DisplayPort-1 -d 1 2 3 4 5
bspc monitor DisplayPort-0 -d 6 7 8 9 10
bspc monitor DisplayPort-2 -d 11 12 13 14 15

bspc rule --add discord desktop=^11
bspc rule --add discord-ptb desktop=^12
bspc rule --add telegram-desktop desktop=^5
bspc rule --add hexchat desktop=^4
bspc rule --add evolution desktop=^2

telegram-desktop &
hexchat &
evolution &
Discord &
discord-ptb &

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sleep 60 & $HOME/.config/polybar/launch.sh &

