#! /bin/sh

sxhkd &
pipewire &
pipewire-pulse &
lxqt-policykit-agent &
setxkbmap -layout ca -model pc105 -option caps:swapescape &
$HOME/.screenlayout/default.sh &
xsetroot -cursor_name left_ptr &

nitrogen --restore &
wired &
syncthingtray &
redshift -l 40.8:-74.4 &
/usr/lib/libexec/kdeconnectd &
kdeconnect-indicator &
nm-tray &

bspc config external_rules_command $HOME/.config/bspwm/external_rules

bspc monitor DisplayPort-2 -d 1 2 3 4 5
bspc monitor DisplayPort-0 -d 6 7 8 9 10
bspc monitor DisplayPort-1 -d 11 12 13 14 15

bspc rule --add discord desktop=^11
bspc rule --add discord-ptb desktop=^12
bspc rule --add telegram-desktop desktop=^5
bspc rule --add hexchat desktop=^4
bspc rule --add evolution desktop=^2

telegram-desktop &
hexchat &
kmail &
kalendar &
Discord &
discord-ptb &

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap           8
bspc config normal_border_color  '#181a1f'
bspc config focused_border_color '#f7a8da'

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

while pgrep -u $UID -f bspwm_window_titles >/dev/null; do pkill -f bspwm_window_titles; done
$HOME/.config/bspwm/bspwm_window_titles -p &

sleep 60 & $HOME/.config/polybar/launch.sh &

