[diff]
    command = "riff"
    pager = "riff"
    args = ["--no-pager", "{{ .Destination }}", "{{ .Target }}"]

[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

[bitwarden]
    command = "rbw"
